spring:
   datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/fresh?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
      username: root
      password: a
   
   http:
      encoding:
         force: true
         charset: utf-8
         enabled: true
        
   session:
      store-type: redis
      
   redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password: 
      timeout: 5000
      jedis: 
         pool: 
            max-active: 8
   
   mail:
      host: smtp.163.com
      username: huathy@163.com
      password: EAYEVGBGFAAFOSCI
      protocol: smtp
      properties:
         mail:
            smtp:
               auth: true
               ssl: 
                  enable: false
      
# mybatis配置 
mybatis:
   mapper-locations: mapper/*Mapper.xml
   #启用别名类所在的包
   type-aliases-package: com.hx.fresh.goods.entity
   
eureka:
   client:
      service-url: 
         defaultZone: http://huathy:123456@127.0.0.1:6868/eureka